# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-25T07:52:50+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class User(BaseModel):
    id: str | None = None
    email: str | None = None


class AuthTokens(BaseModel):
    access: dict[str, Any] | None = None
    refresh: dict[str, Any] | None = None


class UserWithTokens(BaseModel):
    user: User | None = None
    tokens: AuthTokens | None = None


class Workspace(BaseModel):
    field_id: str | None = Field(None, alias='_id')
    name: str | None = None
    slug: str | None = None
    organizationType: str | None = None
    placeType: str | None = None
    settings: dict[str, Any] | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class IntegrationSettings(BaseModel):
    field_id: str | None = Field(None, alias='_id')
    workspaceId: str | None = None
    integrationId: str | None = None
    config: dict[str, Any] | None = None
    isActive: bool | None = None
    lastTestResult: dict[str, Any] | None = None
    lastTestAt: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class TestResult(BaseModel):
    success: bool | None = None
    message: str | None = None
    timestamp: AwareDatetime | None = None
    details: dict[str, Any] | None = None


class IyzicoConfig(BaseModel):
    enabled: bool | None = None
    apiKey: str | None = None
    secretKey: str | None = None
    uri: str | None = None


class MngConfig(BaseModel):
    enabled: bool | None = None
    apiKey: str | None = None
    apiSecret: str | None = None


class TwilioConfig(BaseModel):
    enabled: bool | None = None
    accountSid: str | None = None
    authToken: str | None = None
    phoneNumber: str | None = None


class SlackConfig(BaseModel):
    enabled: bool | None = None
    webhookUrl: str | None = None
    channel: str | None = None
    username: str | None = None


class DiscordConfig(BaseModel):
    enabled: bool | None = None
    webhookUrl: str | None = None
    channel: str | None = None
    username: str | None = None


class HubSpotConfig(BaseModel):
    enabled: bool | None = None
    apiKey: str | None = None
    portalId: str | None = None


class SalesforceConfig(BaseModel):
    enabled: bool | None = None
    clientId: str | None = None
    clientSecret: str | None = None
    username: str | None = None
    password: str | None = None
    securityToken: str | None = None


class SendGridConfig(BaseModel):
    enabled: bool | None = None
    apiKey: str | None = None
    fromEmail: str | None = None
    fromName: str | None = None


class MailgunConfig(BaseModel):
    enabled: bool | None = None
    apiKey: str | None = None
    domain: str | None = None
    fromEmail: str | None = None
    fromName: str | None = None


class ClickUpConfig(BaseModel):
    enabled: bool | None = None
    apiKey: str | None = None
    teamId: str | None = None
    spaceId: str | None = None
    folderId: str | None = None
    listId: str | None = None


class Provider(Enum):
    mailjet = 'mailjet'
    gmail_smtp = 'gmail_smtp'
    custom_smtp = 'custom_smtp'
    sendgrid = 'sendgrid'
    mailgun = 'mailgun'


class MailjetConfig(BaseModel):
    apiKey: str | None = None
    apiSecret: str | None = None
    fromEmail: str | None = None
    fromName: str | None = None
    templates: dict[str, Any] | None = None


class GmailSmtpConfig(BaseModel):
    clientId: str | None = None
    clientSecret: str | None = None
    refreshToken: str | None = None
    fromEmail: str | None = None
    fromName: str | None = None
    templates: dict[str, Any] | None = None


class Auth(BaseModel):
    user: str | None = None
    pass_: str | None = Field(None, alias='pass')


class CustomSmtpConfig(BaseModel):
    host: str | None = None
    port: float | None = None
    secure: bool | None = None
    auth: Auth | None = None
    fromEmail: str | None = None
    fromName: str | None = None
    templates: dict[str, Any] | None = None


class Type(Enum):
    welcome = 'welcome'
    validation = 'validation'
    password_reset = 'password_reset'
    order_created = 'order_created'
    order_notification = 'order_notification'
    event_registration = 'event_registration'
    newsletter = 'newsletter'
    contact_form = 'contact_form'


class EmailTemplate(BaseModel):
    type: Type | None = None
    templateId: str | None = None
    subject: str | None = None
    content: str | None = None
    variables: list[str] | None = None


class IntegrationInfo(BaseModel):
    id: str | None = None
    name: str | None = None
    description: str | None = None
    category: str | None = None
    logo: str | None = None
    website: str | None = None
    documentation: str | None = None
    features: list[str] | None = None


class Error(BaseModel):
    status: str | None = None
    message: str | None = None
    error: str | None = None


class SuccessResponse(BaseModel):
    status: str | None = None
    data: dict[str, Any] | None = None
    message: str | None = None


class Published(BaseModel):
    date: AwareDatetime | None = None
    by: str | None = None


class EditedItem(BaseModel):
    date: AwareDatetime | None = None
    by: str | None = None


class Created(BaseModel):
    date: AwareDatetime | None = None
    by: str | None = None


class Metadata(BaseModel):
    published: Published | None = None
    edited: list[EditedItem] | None = None
    created: Created | None = None


class CreateMenuDto(BaseModel):
    name: str = Field(..., description='Menü adı')
    description: str | None = Field(None, description='Menü açıklaması')
    location: str = Field(..., description='Menü konumu')
    isActive: bool | None = Field(None, description='Menü aktif mi?')


class UpdateMenuDto(BaseModel):
    name: str | None = Field(None, description='Menü adı')
    description: str | None = Field(None, description='Menü açıklaması')
    location: str | None = Field(None, description='Menü konumu')
    isActive: bool | None = Field(None, description='Menü aktif mi?')


class CreateMenuItemDto(BaseModel):
    title: str = Field(..., description='Menü öğesi başlığı')
    url: str = Field(..., description="Menü öğesi URL'i")
    icon: str | None = Field(None, description='Menü öğesi ikonu')
    order: float = Field(..., description='Menü öğesi sırası')
    parent: str | None = Field(None, description="Üst menü öğesi ID'si")
    isActive: bool | None = Field(None, description='Menü öğesi aktif mi?')
    menus: list[str] = Field(..., description="Bu öğenin bulunacağı menü ID'leri")
    category: str | None = Field(None, description="Kategori ID'si")


class UpdateMenuItemDto(BaseModel):
    title: str | None = Field(None, description='Menü öğesi başlığı')
    url: str | None = Field(None, description="Menü öğesi URL'i")
    icon: str | None = Field(None, description='Menü öğesi ikonu')
    order: float | None = Field(None, description='Menü öğesi sırası')
    parent: str | None = Field(None, description="Üst menü öğesi ID'si")
    isActive: bool | None = Field(None, description='Menü öğesi aktif mi?')
    menus: list[str] | None = Field(
        None, description="Bu öğenin bulunacağı menü ID'leri"
    )
    category: str | None = Field(None, description="Kategori ID'si")


class CreateMenuCategoryDto(BaseModel):
    title: str = Field(..., description='Kategori başlığı')
    slug: str = Field(..., description="Kategori slug'ı")
    description: str = Field(..., description='Kategori açıklaması')
    parent: str | None = Field(None, description="Üst kategori ID'si")


class UpdateMenuCategoryDto(BaseModel):
    title: str | None = Field(None, description='Kategori başlığı')
    slug: str | None = Field(None, description="Kategori slug'ı")
    description: str | None = Field(None, description='Kategori açıklaması')
    parent: str | None = Field(None, description="Üst kategori ID'si")


class EmailIntegrationSettings(BaseModel):
    provider: Provider | None = None
    enabled: bool | None = None
    mailjet: MailjetConfig | None = None
    sendgrid: SendGridConfig | None = None
    mailgun: MailgunConfig | None = None
    gmailSmtp: GmailSmtpConfig | None = None
    customSmtp: CustomSmtpConfig | None = None


class Menu(BaseModel):
    field_id: str | None = Field(None, alias='_id')
    name: str = Field(..., description='Menü adı')
    description: str | None = Field(None, description='Menü açıklaması')
    location: str = Field(..., description='Menü konumu (header, footer, sidebar vb.)')
    items: list[MenuItem] | None = Field(None, description='Menü öğeleri')
    isActive: bool | None = Field(None, description='Menü aktif mi?')
    metadata: Metadata | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class MenuItem(BaseModel):
    field_id: str | None = Field(None, alias='_id')
    title: str = Field(..., description='Menü öğesi başlığı')
    url: str = Field(..., description="Menü öğesi URL'i")
    icon: str | None = Field(None, description='Menü öğesi ikonu')
    order: float = Field(..., description='Menü öğesi sırası')
    parent: MenuItem | None = Field(None, description='Üst menü öğesi')
    children: list[MenuItem] | None = Field(None, description='Alt menü öğeleri')
    isActive: bool | None = Field(None, description='Menü öğesi aktif mi?')
    menus: list[Menu] = Field(..., description='Bu öğenin bulunduğu menüler')
    category: MenuCategory | None = Field(None, description='Menü öğesi kategorisi')
    metadata: Metadata | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class MenuCategory(BaseModel):
    field_id: str | None = Field(None, alias='_id')
    title: str = Field(..., description='Kategori başlığı')
    slug: str = Field(..., description="Kategori slug'ı")
    description: str = Field(..., description='Kategori açıklaması')
    items: list[MenuItem] | None = Field(None, description='Kategori öğeleri')
    parent: MenuCategory | None = Field(None, description='Üst kategori')
    children: list[MenuCategory] | None = Field(None, description='Alt kategoriler')
    metadata: Metadata | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


Menu.model_rebuild()
MenuItem.model_rebuild()
